Bump MSRV to 1.76
```
  error: package `toml_datetime v0.7.2` cannot be built because it requires rustc 1.76 or newer, while the currently active rustc version is 1.66.1
  Either upgrade to rustc 1.76 or newer, or use
  cargo update -p toml_datetime@0.7.2 --precise ver
  where `ver` is the latest version of `toml_datetime` supporting rustc 1.66.1
```