toml 0.5.9 requires rustc 1.36+
```
error[E0277]: the trait bound `std::string::String: std::convert::From<&std::string::String>` is not satisfied
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.5.9/src/value.rs:530:56
    |
530 |                     if let Entry::Vacant(vacant) = map.entry(&key) {
    |                                                        ^^^^^ the trait `std::convert::From<&std::string::String>` is not implemented for `std::string::String`
    |
    = help: the following implementations were found:
              <std::string::String as std::convert::From<&'a str>>
              <std::string::String as std::convert::From<std::borrow::Cow<'a, str>>>
              <std::string::String as std::convert::From<std::boxed::Box<str>>>
    = note: required because of the requirements on the impl of `std::convert::Into<std::string::String>` for `&std::string::String`
```

refs: https://github.com/rust-lang/rust/commit/08b0aca05e3709766fd7e0e01ec56a8511e4c46b