Bump MSRV to 1.70
toml_edit (used by toml) requires it.

```
error: package `toml_edit v0.22.6` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0
```