Bump MSRV to 1.67
toml_datetime (used by toml) requires it.

```
error: package `toml_datetime v0.6.5` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.66.1
```