Bump MSRV to 1.69
toml_edit (used by toml) requires it.

```
error: package `toml_edit v0.21.1` cannot be built because it requires rustc 1.69 or newer, while the currently active rustc version is 1.67.1
```