Bump MSRV to 1.60
```
error: failed to select a version for the requirement `toml = "=0.6.0"`
candidate versions found which didn't match: 0.5.11, 0.5.10, 0.5.9, ...
location searched: crates.io index
required by package `find-crate v0.6.3 (/Users/taiki/projects/sources/taiki-e/find-crate)`
```