Bump MSRV to 1.64
winnow (used by toml) requires it.

```
error: package `winnow v0.4.4` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.60.0
```