Bump MSRV to 1.85
```
  error: failed to download replaced source registry `crates-io`

  Caused by:
    failed to parse manifest at `/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/toml_parser-1.1.0+spec-1.1.0/Cargo.toml`

  Caused by:
    feature `edition2024` is required

    The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.76.0 (c84b36747 2024-01-18)).
    Consider trying a newer version of Cargo (this may require the nightly release).
    See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```